services:
  redis:
    image: "redis:latest"
    ports:
    - 6379:6379

  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: admin
    ports:
    - 5432:5432

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_HOST=db
      - VK_API_ACCESS_TOKEN=${VK_API_ACCESS_TOKEN}
      - REDIS_URL=redis://redis:6379
      - REDIS_EX_TIME=5
      - CELERY_BROKER=redis://redis:6379
      - CELERY_BACKEND=redis://redis:6379
      - SCHEDULER_REFRESH_TIME=30
    depends_on:
      - db
      - redis

  updater:
    build: .
    command: python -m info_updates_parser.updates_parser
    volumes:
    - .:/code
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_HOST=db
      - VK_API_ACCESS_TOKEN=${VK_API_ACCESS_TOKEN}
      - REDIS_URL=redis://redis:6379
      - REDIS_EX_TIME=5
      - SCHEDULER_REFRESH_TIME=30

  celery_app:
    build: .
    command: celery -A vk_group_info.celery worker -l DEBUG --pool=solo
    volumes:
    - .:/code
    environment:
      - CELERY_BROKER=redis://redis:6379
      - CELERY_BACKEND=redis://redis:6379
      - REDIS_URL=redis://redis:6379

    depends_on:
      - redis