services:
  redis:
    image: "redis:latest"
    ports:
    - 6379:6379

  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: admin
    ports:
    - 5432:5432

  web:
    build: .
    command: sh run.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_HOST=db
      - VK_API_ACCESS_TOKEN=${VK_API_ACCESS_TOKEN}
      - REDIS_URL=redis://redis:6379
      - REDIS_EX_TIME=5
      - SCHEDULER_REFRESH_TIME=30
    depends_on:
      - db
      - redis