# Generated by Django 4.0.6 on 2022-07-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkGroupModel',
            fields=[
                ('id', models.CharField(max_length=355, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=355)),
                ('user_count', models.IntegerField()),
            ],
        ),
    ]
