# Generated by Django 4.0.6 on 2022-07-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkgroupmodel',
            name='last_update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='vkgroupmodel',
            index=models.Index(fields=['id'], name='vk_groups_v_id_7d6268_idx'),
        ),
    ]
