# Generated by Django 4.0.6 on 2022-07-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_groups', '0002_vkgroupmodel_last_update_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vkgroupmodel',
            index=models.Index(fields=['last_update_at'], name='vk_groups_v_last_up_178a2f_idx'),
        ),
    ]
